# Generated by Django 4.1.3 on 2022-11-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_rename_tecnologias_empresa_tecnologia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='tecnologia',
            new_name='tecnologias',
        ),
        migrations.AlterField(
            model_name='tecnologias',
            name='tecnologia',
            field=models.CharField(max_length=30),
        ),
    ]
